// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger.proto

package ledger

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PublicKey struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}
func (*PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_63585974d4c6a2c4, []int{0}
}

func (m *PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKey.Unmarshal(m, b)
}
func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKey.Marshal(b, m, deterministic)
}
func (m *PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKey.Merge(m, src)
}
func (m *PublicKey) XXX_Size() int {
	return xxx_messageInfo_PublicKey.Size(m)
}
func (m *PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

func (m *PublicKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type ChannelCommit struct {
	Payer                *PublicKey `protobuf:"bytes,1,opt,name=payer,proto3" json:"payer,omitempty"`
	Recipient            *PublicKey `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount               int64      `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PayerId              int64      `protobuf:"varint,4,opt,name=payer_id,json=payerId,proto3" json:"payer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ChannelCommit) Reset()         { *m = ChannelCommit{} }
func (m *ChannelCommit) String() string { return proto.CompactTextString(m) }
func (*ChannelCommit) ProtoMessage()    {}
func (*ChannelCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_63585974d4c6a2c4, []int{1}
}

func (m *ChannelCommit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelCommit.Unmarshal(m, b)
}
func (m *ChannelCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelCommit.Marshal(b, m, deterministic)
}
func (m *ChannelCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelCommit.Merge(m, src)
}
func (m *ChannelCommit) XXX_Size() int {
	return xxx_messageInfo_ChannelCommit.Size(m)
}
func (m *ChannelCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelCommit.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelCommit proto.InternalMessageInfo

func (m *ChannelCommit) GetPayer() *PublicKey {
	if m != nil {
		return m.Payer
	}
	return nil
}

func (m *ChannelCommit) GetRecipient() *PublicKey {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *ChannelCommit) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ChannelCommit) GetPayerId() int64 {
	if m != nil {
		return m.PayerId
	}
	return 0
}

type SignedChannelCommit struct {
	Channel              *ChannelCommit `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Signature            []byte         `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignedChannelCommit) Reset()         { *m = SignedChannelCommit{} }
func (m *SignedChannelCommit) String() string { return proto.CompactTextString(m) }
func (*SignedChannelCommit) ProtoMessage()    {}
func (*SignedChannelCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_63585974d4c6a2c4, []int{2}
}

func (m *SignedChannelCommit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedChannelCommit.Unmarshal(m, b)
}
func (m *SignedChannelCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedChannelCommit.Marshal(b, m, deterministic)
}
func (m *SignedChannelCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedChannelCommit.Merge(m, src)
}
func (m *SignedChannelCommit) XXX_Size() int {
	return xxx_messageInfo_SignedChannelCommit.Size(m)
}
func (m *SignedChannelCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedChannelCommit.DiscardUnknown(m)
}

var xxx_messageInfo_SignedChannelCommit proto.InternalMessageInfo

func (m *SignedChannelCommit) GetChannel() *ChannelCommit {
	if m != nil {
		return m.Channel
	}
	return nil
}

func (m *SignedChannelCommit) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type CreateAccountResult struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResult) Reset()         { *m = CreateAccountResult{} }
func (m *CreateAccountResult) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResult) ProtoMessage()    {}
func (*CreateAccountResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_63585974d4c6a2c4, []int{3}
}

func (m *CreateAccountResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResult.Unmarshal(m, b)
}
func (m *CreateAccountResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResult.Marshal(b, m, deterministic)
}
func (m *CreateAccountResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResult.Merge(m, src)
}
func (m *CreateAccountResult) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResult.Size(m)
}
func (m *CreateAccountResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResult proto.InternalMessageInfo

func (m *CreateAccountResult) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type Account struct {
	Address *PublicKey `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Current available balance
	Balance              int64    `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_63585974d4c6a2c4, []int{4}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAddress() *PublicKey {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Account) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type ChannelID struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelID) Reset()         { *m = ChannelID{} }
func (m *ChannelID) String() string { return proto.CompactTextString(m) }
func (*ChannelID) ProtoMessage()    {}
func (*ChannelID) Descriptor() ([]byte, []int) {
	return fileDescriptor_63585974d4c6a2c4, []int{5}
}

func (m *ChannelID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelID.Unmarshal(m, b)
}
func (m *ChannelID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelID.Marshal(b, m, deterministic)
}
func (m *ChannelID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelID.Merge(m, src)
}
func (m *ChannelID) XXX_Size() int {
	return xxx_messageInfo_ChannelID.Size(m)
}
func (m *ChannelID) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelID.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelID proto.InternalMessageInfo

func (m *ChannelID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ChannelInfo struct {
	Id                   *ChannelID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromAccount          *Account   `protobuf:"bytes,2,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount            *Account   `protobuf:"bytes,3,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	CloseSequence        int64      `protobuf:"varint,4,opt,name=close_sequence,json=closeSequence,proto3" json:"close_sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ChannelInfo) Reset()         { *m = ChannelInfo{} }
func (m *ChannelInfo) String() string { return proto.CompactTextString(m) }
func (*ChannelInfo) ProtoMessage()    {}
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_63585974d4c6a2c4, []int{6}
}

func (m *ChannelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInfo.Unmarshal(m, b)
}
func (m *ChannelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInfo.Marshal(b, m, deterministic)
}
func (m *ChannelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInfo.Merge(m, src)
}
func (m *ChannelInfo) XXX_Size() int {
	return xxx_messageInfo_ChannelInfo.Size(m)
}
func (m *ChannelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInfo proto.InternalMessageInfo

func (m *ChannelInfo) GetId() *ChannelID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ChannelInfo) GetFromAccount() *Account {
	if m != nil {
		return m.FromAccount
	}
	return nil
}

func (m *ChannelInfo) GetToAccount() *Account {
	if m != nil {
		return m.ToAccount
	}
	return nil
}

func (m *ChannelInfo) GetCloseSequence() int64 {
	if m != nil {
		return m.CloseSequence
	}
	return 0
}

type SignedChannelState struct {
	Channel              *ChannelState `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	FromSignature        []byte        `protobuf:"bytes,2,opt,name=from_signature,json=fromSignature,proto3" json:"from_signature,omitempty"`
	ToSignature          []byte        `protobuf:"bytes,3,opt,name=to_signature,json=toSignature,proto3" json:"to_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SignedChannelState) Reset()         { *m = SignedChannelState{} }
func (m *SignedChannelState) String() string { return proto.CompactTextString(m) }
func (*SignedChannelState) ProtoMessage()    {}
func (*SignedChannelState) Descriptor() ([]byte, []int) {
	return fileDescriptor_63585974d4c6a2c4, []int{7}
}

func (m *SignedChannelState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedChannelState.Unmarshal(m, b)
}
func (m *SignedChannelState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedChannelState.Marshal(b, m, deterministic)
}
func (m *SignedChannelState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedChannelState.Merge(m, src)
}
func (m *SignedChannelState) XXX_Size() int {
	return xxx_messageInfo_SignedChannelState.Size(m)
}
func (m *SignedChannelState) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedChannelState.DiscardUnknown(m)
}

var xxx_messageInfo_SignedChannelState proto.InternalMessageInfo

func (m *SignedChannelState) GetChannel() *ChannelState {
	if m != nil {
		return m.Channel
	}
	return nil
}

func (m *SignedChannelState) GetFromSignature() []byte {
	if m != nil {
		return m.FromSignature
	}
	return nil
}

func (m *SignedChannelState) GetToSignature() []byte {
	if m != nil {
		return m.ToSignature
	}
	return nil
}

type ClosedChannelCursor struct {
	Payer                *PublicKey `protobuf:"bytes,1,opt,name=payer,proto3" json:"payer,omitempty"`
	CloseSequence        int64      `protobuf:"varint,2,opt,name=close_sequence,json=closeSequence,proto3" json:"close_sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ClosedChannelCursor) Reset()         { *m = ClosedChannelCursor{} }
func (m *ClosedChannelCursor) String() string { return proto.CompactTextString(m) }
func (*ClosedChannelCursor) ProtoMessage()    {}
func (*ClosedChannelCursor) Descriptor() ([]byte, []int) {
	return fileDescriptor_63585974d4c6a2c4, []int{8}
}

func (m *ClosedChannelCursor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClosedChannelCursor.Unmarshal(m, b)
}
func (m *ClosedChannelCursor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClosedChannelCursor.Marshal(b, m, deterministic)
}
func (m *ClosedChannelCursor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClosedChannelCursor.Merge(m, src)
}
func (m *ClosedChannelCursor) XXX_Size() int {
	return xxx_messageInfo_ClosedChannelCursor.Size(m)
}
func (m *ClosedChannelCursor) XXX_DiscardUnknown() {
	xxx_messageInfo_ClosedChannelCursor.DiscardUnknown(m)
}

var xxx_messageInfo_ClosedChannelCursor proto.InternalMessageInfo

func (m *ClosedChannelCursor) GetPayer() *PublicKey {
	if m != nil {
		return m.Payer
	}
	return nil
}

func (m *ClosedChannelCursor) GetCloseSequence() int64 {
	if m != nil {
		return m.CloseSequence
	}
	return 0
}

type ChannelState struct {
	Id                   *ChannelID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sequence             int64      `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	From                 *Account   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Account   `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ChannelState) Reset()         { *m = ChannelState{} }
func (m *ChannelState) String() string { return proto.CompactTextString(m) }
func (*ChannelState) ProtoMessage()    {}
func (*ChannelState) Descriptor() ([]byte, []int) {
	return fileDescriptor_63585974d4c6a2c4, []int{9}
}

func (m *ChannelState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelState.Unmarshal(m, b)
}
func (m *ChannelState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelState.Marshal(b, m, deterministic)
}
func (m *ChannelState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelState.Merge(m, src)
}
func (m *ChannelState) XXX_Size() int {
	return xxx_messageInfo_ChannelState.Size(m)
}
func (m *ChannelState) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelState.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelState proto.InternalMessageInfo

func (m *ChannelState) GetId() *ChannelID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ChannelState) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ChannelState) GetFrom() *Account {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ChannelState) GetTo() *Account {
	if m != nil {
		return m.To
	}
	return nil
}

type ChannelClosed struct {
	State                *SignedChannelState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ChannelClosed) Reset()         { *m = ChannelClosed{} }
func (m *ChannelClosed) String() string { return proto.CompactTextString(m) }
func (*ChannelClosed) ProtoMessage()    {}
func (*ChannelClosed) Descriptor() ([]byte, []int) {
	return fileDescriptor_63585974d4c6a2c4, []int{10}
}

func (m *ChannelClosed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelClosed.Unmarshal(m, b)
}
func (m *ChannelClosed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelClosed.Marshal(b, m, deterministic)
}
func (m *ChannelClosed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelClosed.Merge(m, src)
}
func (m *ChannelClosed) XXX_Size() int {
	return xxx_messageInfo_ChannelClosed.Size(m)
}
func (m *ChannelClosed) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelClosed.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelClosed proto.InternalMessageInfo

func (m *ChannelClosed) GetState() *SignedChannelState {
	if m != nil {
		return m.State
	}
	return nil
}

func init() {
	proto.RegisterType((*PublicKey)(nil), "ledger.PublicKey")
	proto.RegisterType((*ChannelCommit)(nil), "ledger.ChannelCommit")
	proto.RegisterType((*SignedChannelCommit)(nil), "ledger.SignedChannelCommit")
	proto.RegisterType((*CreateAccountResult)(nil), "ledger.CreateAccountResult")
	proto.RegisterType((*Account)(nil), "ledger.Account")
	proto.RegisterType((*ChannelID)(nil), "ledger.ChannelID")
	proto.RegisterType((*ChannelInfo)(nil), "ledger.ChannelInfo")
	proto.RegisterType((*SignedChannelState)(nil), "ledger.SignedChannelState")
	proto.RegisterType((*ClosedChannelCursor)(nil), "ledger.ClosedChannelCursor")
	proto.RegisterType((*ChannelState)(nil), "ledger.ChannelState")
	proto.RegisterType((*ChannelClosed)(nil), "ledger.ChannelClosed")
}

func init() { proto.RegisterFile("ledger.proto", fileDescriptor_63585974d4c6a2c4) }

var fileDescriptor_63585974d4c6a2c4 = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x51, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0xed, 0xb6, 0x6e, 0x26, 0x4e, 0x80, 0x49, 0x41, 0xc1, 0x05, 0xd1, 0x2e, 0xaa, 0x28,
	0x42, 0x4a, 0x51, 0xf8, 0xe3, 0x8b, 0x2a, 0x48, 0x55, 0x41, 0x42, 0x95, 0x73, 0x80, 0xc8, 0xb1,
	0x27, 0xc1, 0xc2, 0xf1, 0x06, 0x7b, 0x2d, 0x91, 0x4b, 0xf0, 0xc3, 0x2f, 0x37, 0xe1, 0x2c, 0xdc,
	0x05, 0x79, 0xed, 0xb5, 0x93, 0xd8, 0x41, 0xfd, 0xf3, 0xbe, 0x79, 0x33, 0xf3, 0x9e, 0x67, 0x76,
	0xc1, 0x0a, 0xc9, 0x5f, 0x50, 0x3c, 0x5c, 0xc5, 0x5c, 0x70, 0x3c, 0xca, 0x4f, 0xec, 0x39, 0xb4,
	0xef, 0xd2, 0x59, 0x18, 0x78, 0x9f, 0x69, 0x8d, 0x0f, 0xc1, 0xf8, 0x46, 0xeb, 0x81, 0x76, 0xa6,
	0x5d, 0x5a, 0x4e, 0xf6, 0xc9, 0x7e, 0x6b, 0xd0, 0x1d, 0x7f, 0x75, 0xa3, 0x88, 0xc2, 0x31, 0x5f,
	0x2e, 0x03, 0x81, 0xaf, 0xe0, 0x70, 0xe5, 0xae, 0x29, 0x96, 0xac, 0xce, 0xe8, 0xd1, 0xb0, 0x28,
	0x5b, 0x56, 0x71, 0xf2, 0x38, 0x5e, 0x41, 0x3b, 0x26, 0x2f, 0x58, 0x05, 0x14, 0x89, 0x81, 0xbe,
	0x8f, 0x5c, 0x71, 0xf0, 0x09, 0x1c, 0xb9, 0x4b, 0x9e, 0x46, 0x62, 0x60, 0x9c, 0x69, 0x97, 0x86,
	0x53, 0x9c, 0xf0, 0x29, 0x1c, 0xcb, 0x8a, 0xd3, 0xc0, 0x1f, 0x1c, 0xc8, 0x88, 0x29, 0xcf, 0xb7,
	0x3e, 0xf3, 0xa1, 0x3f, 0x09, 0x16, 0x11, 0xf9, 0xdb, 0x1a, 0xaf, 0xc0, 0xf4, 0x72, 0xa0, 0x50,
	0xf9, 0x58, 0x35, 0xde, 0xe2, 0x39, 0x8a, 0x85, 0xcf, 0xa0, 0x9d, 0x04, 0x8b, 0xc8, 0x15, 0x69,
	0x4c, 0x52, 0xab, 0xe5, 0x54, 0x00, 0xfb, 0x00, 0xfd, 0x71, 0x4c, 0xae, 0xa0, 0x6b, 0xcf, 0xcb,
	0x14, 0x39, 0x94, 0xa4, 0xa1, 0xc0, 0xd7, 0x60, 0xba, 0x39, 0x50, 0x74, 0x79, 0xa0, 0xba, 0x28,
	0x9e, 0x8a, 0xb3, 0x3b, 0x30, 0x0b, 0x0c, 0xdf, 0x80, 0xe9, 0xfa, 0x7e, 0x4c, 0x49, 0xb2, 0xff,
	0x0f, 0x2a, 0x06, 0x0e, 0xc0, 0x9c, 0xb9, 0xa1, 0x1b, 0x79, 0xb9, 0x2a, 0xc3, 0x51, 0x47, 0x76,
	0x0a, 0xed, 0xc2, 0xcb, 0xed, 0x47, 0xec, 0x81, 0x1e, 0xf8, 0xb2, 0x9c, 0xe1, 0xe8, 0x81, 0xcf,
	0xfe, 0x68, 0xd0, 0x51, 0xd1, 0x68, 0xce, 0xf1, 0xbc, 0x8c, 0x6f, 0xb4, 0x2b, 0xd3, 0xb3, 0x14,
	0x1c, 0x81, 0x35, 0x8f, 0xf9, 0x72, 0xaa, 0x1c, 0xe9, 0xcd, 0x8e, 0x3a, 0x19, 0x49, 0x59, 0x19,
	0x02, 0x08, 0x5e, 0x66, 0x18, 0xcd, 0x19, 0x6d, 0xc1, 0x15, 0xff, 0x02, 0x7a, 0x5e, 0xc8, 0x13,
	0x9a, 0x26, 0xf4, 0x3d, 0xa5, 0xcc, 0x54, 0x3e, 0xce, 0xae, 0x44, 0x27, 0x05, 0xc8, 0x7e, 0x6a,
	0x80, 0x5b, 0x53, 0x9d, 0x08, 0x57, 0x10, 0x0e, 0x77, 0x87, 0x7a, 0xb2, 0xe3, 0x44, 0xd2, 0xaa,
	0x99, 0x5e, 0x40, 0x4f, 0x3a, 0xda, 0x1d, 0x6c, 0x37, 0x43, 0x27, 0x0a, 0xc4, 0x73, 0xb0, 0x04,
	0xdf, 0x20, 0x19, 0x92, 0xd4, 0x11, 0xbc, 0xa4, 0x30, 0x82, 0xfe, 0x38, 0x53, 0x58, 0x6e, 0x59,
	0x1a, 0x27, 0x3c, 0xbe, 0xff, 0x4d, 0xa8, 0xfb, 0xd6, 0x9b, 0x7c, 0xff, 0xd2, 0xc0, 0xda, 0x72,
	0x7c, 0x8f, 0xb1, 0xd9, 0x70, 0xbc, 0x53, 0xb4, 0x3c, 0xe3, 0x4b, 0x38, 0xc8, 0xac, 0xee, 0x1b,
	0x8c, 0x0c, 0xe2, 0x0b, 0xd0, 0x05, 0x97, 0x73, 0x68, 0xa0, 0xe8, 0x82, 0xb3, 0xeb, 0xea, 0x01,
	0x90, 0xff, 0x00, 0xdf, 0xc2, 0x61, 0x92, 0xc9, 0x2b, 0x84, 0xd9, 0x2a, 0xa9, 0x3e, 0x32, 0x27,
	0x27, 0x8e, 0xfe, 0xea, 0x70, 0x5c, 0xe0, 0x09, 0x66, 0xf5, 0xe4, 0x65, 0x2a, 0x10, 0x3c, 0x6d,
	0x2c, 0x90, 0xdf, 0x50, 0xbb, 0x6e, 0x9b, 0xb5, 0xf0, 0x3d, 0xf4, 0x6e, 0x48, 0x6c, 0x2e, 0x78,
	0x9d, 0x66, 0xf7, 0x77, 0xa1, 0x68, 0xce, 0x59, 0x0b, 0xc7, 0x60, 0x49, 0x1f, 0xaa, 0xfb, 0x7f,
	0xe4, 0xdb, 0xb5, 0x57, 0x43, 0xfe, 0x00, 0xd6, 0xc2, 0x4f, 0x70, 0x72, 0x43, 0xe2, 0x0b, 0xfd,
	0x10, 0x5b, 0x7b, 0x51, 0x59, 0x69, 0x58, 0x97, 0x7d, 0x82, 0xca, 0xff, 0xa1, 0x6e, 0x49, 0x7d,
	0x8f, 0xec, 0xaa, 0x6e, 0xfd, 0x19, 0x62, 0xad, 0xd9, 0x91, 0x7c, 0xd2, 0xdf, 0xfd, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0xce, 0x15, 0x5a, 0x4f, 0xe2, 0x05, 0x00, 0x00,
}
