// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/TRON-US/go-btfs/protos/host/hosts.proto

package hostpb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/tron-us/protobuf/gogoproto"
	proto "github.com/tron-us/protobuf/proto"
	github_com_tron_us_protobuf_types "github.com/tron-us/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HostShardStatus struct {
	Status               string    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty" pg:"status"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" pg:"message"`
	LastUpdated          time.Time `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3,stdtime" json:"last_updated" pg:"last_updated"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" pg:"-"`
	XXX_unrecognized     []byte    `json:"-" pg:"-"`
	XXX_sizecache        int32     `json:"-" pg:"-"`
}

func (m *HostShardStatus) Reset()         { *m = HostShardStatus{} }
func (m *HostShardStatus) String() string { return proto.CompactTextString(m) }
func (*HostShardStatus) ProtoMessage()    {}
func (*HostShardStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_e33c81a5937fe6ca, []int{0}
}
func (m *HostShardStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HostShardStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HostShardStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HostShardStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostShardStatus.Merge(m, src)
}
func (m *HostShardStatus) XXX_Size() int {
	return m.Size()
}
func (m *HostShardStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_HostShardStatus.DiscardUnknown(m)
}

var xxx_messageInfo_HostShardStatus proto.InternalMessageInfo

func (m *HostShardStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *HostShardStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HostShardStatus) GetLastUpdated() time.Time {
	if m != nil {
		return m.LastUpdated
	}
	return time.Time{}
}

func (*HostShardStatus) XXX_MessageName() string {
	return "host.HostShardStatus"
}

type HostShardSignedContracts struct {
	SignedEscrowContract []byte   `protobuf:"bytes,1,opt,name=signed_escrow_contract,json=signedEscrowContract,proto3" json:"signed_escrow_contract,omitempty" pg:"signed_escrow_contract"`
	SignedGuardContract  []byte   `protobuf:"bytes,2,opt,name=signed_guard_contract,json=signedGuardContract,proto3" json:"signed_guard_contract,omitempty" pg:"signed_guard_contract"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" pg:"-"`
	XXX_unrecognized     []byte   `json:"-" pg:"-"`
	XXX_sizecache        int32    `json:"-" pg:"-"`
}

func (m *HostShardSignedContracts) Reset()         { *m = HostShardSignedContracts{} }
func (m *HostShardSignedContracts) String() string { return proto.CompactTextString(m) }
func (*HostShardSignedContracts) ProtoMessage()    {}
func (*HostShardSignedContracts) Descriptor() ([]byte, []int) {
	return fileDescriptor_e33c81a5937fe6ca, []int{1}
}
func (m *HostShardSignedContracts) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HostShardSignedContracts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HostShardSignedContracts.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HostShardSignedContracts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostShardSignedContracts.Merge(m, src)
}
func (m *HostShardSignedContracts) XXX_Size() int {
	return m.Size()
}
func (m *HostShardSignedContracts) XXX_DiscardUnknown() {
	xxx_messageInfo_HostShardSignedContracts.DiscardUnknown(m)
}

var xxx_messageInfo_HostShardSignedContracts proto.InternalMessageInfo

func (m *HostShardSignedContracts) GetSignedEscrowContract() []byte {
	if m != nil {
		return m.SignedEscrowContract
	}
	return nil
}

func (m *HostShardSignedContracts) GetSignedGuardContract() []byte {
	if m != nil {
		return m.SignedGuardContract
	}
	return nil
}

func (*HostShardSignedContracts) XXX_MessageName() string {
	return "host.HostShardSignedContracts"
}
func init() {
	proto.RegisterType((*HostShardStatus)(nil), "host.HostShardStatus")
	golang_proto.RegisterType((*HostShardStatus)(nil), "host.HostShardStatus")
	proto.RegisterType((*HostShardSignedContracts)(nil), "host.HostShardSignedContracts")
	golang_proto.RegisterType((*HostShardSignedContracts)(nil), "host.HostShardSignedContracts")
}

func init() {
	proto.RegisterFile("github.com/TRON-US/go-btfs/protos/host/hosts.proto", fileDescriptor_e33c81a5937fe6ca)
}
func init() {
	golang_proto.RegisterFile("github.com/TRON-US/go-btfs/protos/host/hosts.proto", fileDescriptor_e33c81a5937fe6ca)
}

var fileDescriptor_e33c81a5937fe6ca = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x4d, 0x4f, 0xfa, 0x40,
	0x10, 0xc6, 0xff, 0xcb, 0xdf, 0xa0, 0x2c, 0x24, 0x26, 0x55, 0x49, 0xc3, 0xa1, 0x10, 0x4e, 0x5c,
	0x68, 0x0d, 0x7a, 0x37, 0xc1, 0x18, 0x3c, 0x29, 0x29, 0x70, 0xf1, 0x42, 0xb6, 0x2f, 0x2c, 0x4d,
	0x28, 0xd3, 0x74, 0xa6, 0xf1, 0x0b, 0x78, 0xf4, 0xe0, 0xd1, 0x8f, 0xe3, 0x91, 0xa3, 0x9f, 0xc0,
	0x17, 0xf8, 0x12, 0x1e, 0xcd, 0x6e, 0xdb, 0xe0, 0x65, 0xb3, 0xcf, 0x3c, 0xf3, 0xcb, 0x3c, 0x93,
	0xe1, 0x03, 0x19, 0xd1, 0x32, 0xf3, 0x6c, 0x1f, 0x62, 0x67, 0xea, 0xde, 0xdf, 0xf5, 0x67, 0x13,
	0x47, 0x42, 0xdf, 0xa3, 0x05, 0x3a, 0x49, 0x0a, 0x04, 0xe8, 0x2c, 0x01, 0x49, 0x3f, 0x68, 0xeb,
	0x8a, 0x71, 0xa0, 0x44, 0xeb, 0xfc, 0x0f, 0x49, 0x29, 0xac, 0xfb, 0x59, 0x41, 0x78, 0xd9, 0xc2,
	0x91, 0x20, 0x41, 0x0b, 0xfd, 0xcb, 0xb9, 0x56, 0x5b, 0x02, 0xc8, 0x55, 0xb8, 0xef, 0xa2, 0x28,
	0x0e, 0x91, 0x44, 0x9c, 0xe4, 0x0d, 0xdd, 0x67, 0xc6, 0x8f, 0x6f, 0x01, 0x69, 0xb2, 0x14, 0x69,
	0x30, 0x21, 0x41, 0x19, 0x1a, 0x4d, 0x5e, 0x45, 0xfd, 0x33, 0x59, 0x87, 0xf5, 0x6a, 0x6e, 0xa1,
	0x0c, 0x93, 0x1f, 0xc6, 0x21, 0xa2, 0x90, 0xa1, 0x59, 0xd1, 0x46, 0x29, 0x8d, 0x11, 0x6f, 0xac,
	0x04, 0xd2, 0x3c, 0x4b, 0x02, 0x41, 0x61, 0x60, 0xfe, 0xef, 0xb0, 0x5e, 0x7d, 0xd0, 0xb2, 0xf3,
	0xe9, 0x76, 0x39, 0xdd, 0x9e, 0x96, 0xd3, 0x87, 0x47, 0x9b, 0x8f, 0xf6, 0xbf, 0x97, 0xcf, 0x36,
	0x73, 0xeb, 0x8a, 0x9c, 0xe5, 0x60, 0xf7, 0x89, 0x71, 0x73, 0x1f, 0x27, 0x92, 0xeb, 0x30, 0xb8,
	0x86, 0x35, 0xa5, 0xc2, 0x27, 0x34, 0x2e, 0x79, 0x13, 0x75, 0x69, 0x1e, 0xa2, 0x9f, 0xc2, 0xe3,
	0xdc, 0x2f, 0x2c, 0x9d, 0xb3, 0xe1, 0x9e, 0xe6, 0xee, 0x8d, 0x36, 0x4b, 0xcc, 0x18, 0xf0, 0xb3,
	0x82, 0x92, 0x99, 0x48, 0x83, 0x3d, 0x54, 0xd1, 0xd0, 0x49, 0x6e, 0x8e, 0x94, 0x57, 0x32, 0xc3,
	0xab, 0x9f, 0x6f, 0x8b, 0x6d, 0xb6, 0x16, 0x7b, 0xdf, 0x5a, 0xec, 0x6b, 0x6b, 0xb1, 0xd7, 0x9d,
	0xc5, 0xde, 0x76, 0x16, 0xdb, 0xec, 0x2c, 0xc6, 0x1b, 0x11, 0xd8, 0xea, 0x5a, 0xb6, 0x3a, 0xca,
	0xb0, 0xa6, 0xf2, 0x8e, 0xd5, 0x86, 0x63, 0xf6, 0x50, 0x55, 0xa5, 0xc4, 0xf3, 0xaa, 0x7a, 0xe5,
	0x8b, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x59, 0x7e, 0x08, 0x88, 0xec, 0x01, 0x00, 0x00,
}

func (m *HostShardStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HostShardStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HostShardStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	n1, err1 := github_com_tron_us_protobuf_types.StdTimeMarshalTo(m.LastUpdated, dAtA[i-github_com_tron_us_protobuf_types.SizeOfStdTime(m.LastUpdated):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintHosts(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x1a
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintHosts(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintHosts(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HostShardSignedContracts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HostShardSignedContracts) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HostShardSignedContracts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.SignedGuardContract) > 0 {
		i -= len(m.SignedGuardContract)
		copy(dAtA[i:], m.SignedGuardContract)
		i = encodeVarintHosts(dAtA, i, uint64(len(m.SignedGuardContract)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SignedEscrowContract) > 0 {
		i -= len(m.SignedEscrowContract)
		copy(dAtA[i:], m.SignedEscrowContract)
		i = encodeVarintHosts(dAtA, i, uint64(len(m.SignedEscrowContract)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintHosts(dAtA []byte, offset int, v uint64) int {
	offset -= sovHosts(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedHostShardStatus(r randyHosts, easy bool) *HostShardStatus {
	this := &HostShardStatus{}
	this.Status = string(randStringHosts(r))
	this.Message = string(randStringHosts(r))
	v1 := github_com_tron_us_protobuf_types.NewPopulatedStdTime(r, easy)
	this.LastUpdated = *v1
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedHosts(r, 4)
	}
	return this
}

func NewPopulatedHostShardSignedContracts(r randyHosts, easy bool) *HostShardSignedContracts {
	this := &HostShardSignedContracts{}
	v2 := r.Intn(100)
	this.SignedEscrowContract = make([]byte, v2)
	for i := 0; i < v2; i++ {
		this.SignedEscrowContract[i] = byte(r.Intn(256))
	}
	v3 := r.Intn(100)
	this.SignedGuardContract = make([]byte, v3)
	for i := 0; i < v3; i++ {
		this.SignedGuardContract[i] = byte(r.Intn(256))
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedHosts(r, 3)
	}
	return this
}

type randyHosts interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneHosts(r randyHosts) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringHosts(r randyHosts) string {
	v4 := r.Intn(100)
	tmps := make([]rune, v4)
	for i := 0; i < v4; i++ {
		tmps[i] = randUTF8RuneHosts(r)
	}
	return string(tmps)
}
func randUnrecognizedHosts(r randyHosts, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldHosts(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldHosts(dAtA []byte, r randyHosts, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateHosts(dAtA, uint64(key))
		v5 := r.Int63()
		if r.Intn(2) == 0 {
			v5 *= -1
		}
		dAtA = encodeVarintPopulateHosts(dAtA, uint64(v5))
	case 1:
		dAtA = encodeVarintPopulateHosts(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateHosts(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateHosts(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateHosts(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateHosts(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *HostShardStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovHosts(uint64(l))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovHosts(uint64(l))
	}
	l = github_com_tron_us_protobuf_types.SizeOfStdTime(m.LastUpdated)
	n += 1 + l + sovHosts(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *HostShardSignedContracts) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SignedEscrowContract)
	if l > 0 {
		n += 1 + l + sovHosts(uint64(l))
	}
	l = len(m.SignedGuardContract)
	if l > 0 {
		n += 1 + l + sovHosts(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovHosts(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHosts(x uint64) (n int) {
	return sovHosts(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HostShardStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHosts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HostShardStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HostShardStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHosts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdated", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHosts
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_tron_us_protobuf_types.StdTimeUnmarshal(&m.LastUpdated, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHosts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHosts
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHosts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HostShardSignedContracts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHosts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HostShardSignedContracts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HostShardSignedContracts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedEscrowContract", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHosts
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignedEscrowContract = append(m.SignedEscrowContract[:0], dAtA[iNdEx:postIndex]...)
			if m.SignedEscrowContract == nil {
				m.SignedEscrowContract = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedGuardContract", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHosts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHosts
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHosts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignedGuardContract = append(m.SignedGuardContract[:0], dAtA[iNdEx:postIndex]...)
			if m.SignedGuardContract == nil {
				m.SignedGuardContract = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHosts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHosts
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHosts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHosts(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHosts
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHosts
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHosts
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHosts
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHosts
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHosts
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHosts        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHosts          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHosts = fmt.Errorf("proto: unexpected end of group")
)
