// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/TRON-US/go-btfs/protos/shard/shard.proto

package shardpb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	guard "github.com/tron-us/go-btfs-common/protos/guard"
	_ "github.com/tron-us/protobuf/gogoproto"
	proto "github.com/tron-us/protobuf/proto"
	github_com_tron_us_protobuf_types "github.com/tron-us/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Status struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty" pg:"status"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" pg:"message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" pg:"-"`
	XXX_unrecognized     []byte   `json:"-" pg:"-"`
	XXX_sizecache        int32    `json:"-" pg:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9822aadeb9bcd5, []int{0}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Status.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return m.Size()
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (*Status) XXX_MessageName() string {
	return "shard.Status"
}

type Metadata struct {
	Index                int32         `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty" pg:"index"`
	SessionId            string        `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty" pg:"session_id"`
	FileHash             string        `protobuf:"bytes,3,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty" pg:"file_hash"`
	ShardFileSize        int64         `protobuf:"varint,4,opt,name=shard_file_size,json=shardFileSize,proto3" json:"shard_file_size,omitempty" pg:"shard_file_size"`
	StorageLength        int64         `protobuf:"varint,5,opt,name=storage_length,json=storageLength,proto3" json:"storage_length,omitempty" pg:"storage_length"`
	ContractId           string        `protobuf:"bytes,6,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty" pg:"contract_id"`
	Receiver             string        `protobuf:"bytes,7,opt,name=receiver,proto3" json:"receiver,omitempty" pg:"receiver"`
	Price                int64         `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty" pg:"price"`
	TotalPay             int64         `protobuf:"varint,9,opt,name=total_pay,json=totalPay,proto3" json:"total_pay,omitempty" pg:"total_pay"`
	StartTime            time.Time     `protobuf:"bytes,10,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" pg:"start_time"`
	ContractLength       time.Duration `protobuf:"bytes,11,opt,name=contract_length,json=contractLength,proto3,stdduration" json:"contract_length" pg:"contract_length"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" pg:"-"`
	XXX_unrecognized     []byte        `json:"-" pg:"-"`
	XXX_sizecache        int32         `json:"-" pg:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9822aadeb9bcd5, []int{1}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return m.Size()
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Metadata) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Metadata) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *Metadata) GetShardFileSize() int64 {
	if m != nil {
		return m.ShardFileSize
	}
	return 0
}

func (m *Metadata) GetStorageLength() int64 {
	if m != nil {
		return m.StorageLength
	}
	return 0
}

func (m *Metadata) GetContractId() string {
	if m != nil {
		return m.ContractId
	}
	return ""
}

func (m *Metadata) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Metadata) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Metadata) GetTotalPay() int64 {
	if m != nil {
		return m.TotalPay
	}
	return 0
}

func (m *Metadata) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *Metadata) GetContractLength() time.Duration {
	if m != nil {
		return m.ContractLength
	}
	return 0
}

func (*Metadata) XXX_MessageName() string {
	return "shard.Metadata"
}

type Contracts struct {
	HalfSignedEscrowContract []byte   `protobuf:"bytes,1,opt,name=half_signed_escrow_contract,json=halfSignedEscrowContract,proto3" json:"half_signed_escrow_contract,omitempty" pg:"half_signed_escrow_contract"`
	HalfSignedGuardContract  []byte   `protobuf:"bytes,2,opt,name=half_signed_guard_contract,json=halfSignedGuardContract,proto3" json:"half_signed_guard_contract,omitempty" pg:"half_signed_guard_contract"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-" pg:"-"`
	XXX_unrecognized         []byte   `json:"-" pg:"-"`
	XXX_sizecache            int32    `json:"-" pg:"-"`
}

func (m *Contracts) Reset()         { *m = Contracts{} }
func (m *Contracts) String() string { return proto.CompactTextString(m) }
func (*Contracts) ProtoMessage()    {}
func (*Contracts) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9822aadeb9bcd5, []int{2}
}
func (m *Contracts) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Contracts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Contracts.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Contracts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contracts.Merge(m, src)
}
func (m *Contracts) XXX_Size() int {
	return m.Size()
}
func (m *Contracts) XXX_DiscardUnknown() {
	xxx_messageInfo_Contracts.DiscardUnknown(m)
}

var xxx_messageInfo_Contracts proto.InternalMessageInfo

func (m *Contracts) GetHalfSignedEscrowContract() []byte {
	if m != nil {
		return m.HalfSignedEscrowContract
	}
	return nil
}

func (m *Contracts) GetHalfSignedGuardContract() []byte {
	if m != nil {
		return m.HalfSignedGuardContract
	}
	return nil
}

func (*Contracts) XXX_MessageName() string {
	return "shard.Contracts"
}

type SingedContracts struct {
	SignedEscrowContract []byte          `protobuf:"bytes,1,opt,name=signed_escrow_contract,json=signedEscrowContract,proto3" json:"signed_escrow_contract,omitempty" pg:"signed_escrow_contract"`
	GuardContract        *guard.Contract `protobuf:"bytes,2,opt,name=guard_contract,json=guardContract,proto3" json:"guard_contract,omitempty" pg:"guard_contract"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-" pg:"-"`
	XXX_unrecognized     []byte          `json:"-" pg:"-"`
	XXX_sizecache        int32           `json:"-" pg:"-"`
}

func (m *SingedContracts) Reset()         { *m = SingedContracts{} }
func (m *SingedContracts) String() string { return proto.CompactTextString(m) }
func (*SingedContracts) ProtoMessage()    {}
func (*SingedContracts) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9822aadeb9bcd5, []int{3}
}
func (m *SingedContracts) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SingedContracts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SingedContracts.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SingedContracts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingedContracts.Merge(m, src)
}
func (m *SingedContracts) XXX_Size() int {
	return m.Size()
}
func (m *SingedContracts) XXX_DiscardUnknown() {
	xxx_messageInfo_SingedContracts.DiscardUnknown(m)
}

var xxx_messageInfo_SingedContracts proto.InternalMessageInfo

func (m *SingedContracts) GetSignedEscrowContract() []byte {
	if m != nil {
		return m.SignedEscrowContract
	}
	return nil
}

func (m *SingedContracts) GetGuardContract() *guard.Contract {
	if m != nil {
		return m.GuardContract
	}
	return nil
}

func (*SingedContracts) XXX_MessageName() string {
	return "shard.SingedContracts"
}
func init() {
	proto.RegisterType((*Status)(nil), "shard.Status")
	golang_proto.RegisterType((*Status)(nil), "shard.Status")
	proto.RegisterType((*Metadata)(nil), "shard.Metadata")
	golang_proto.RegisterType((*Metadata)(nil), "shard.Metadata")
	proto.RegisterType((*Contracts)(nil), "shard.Contracts")
	golang_proto.RegisterType((*Contracts)(nil), "shard.Contracts")
	proto.RegisterType((*SingedContracts)(nil), "shard.SingedContracts")
	golang_proto.RegisterType((*SingedContracts)(nil), "shard.SingedContracts")
}

func init() {
	proto.RegisterFile("github.com/TRON-US/go-btfs/protos/shard/shard.proto", fileDescriptor_ae9822aadeb9bcd5)
}
func init() {
	golang_proto.RegisterFile("github.com/TRON-US/go-btfs/protos/shard/shard.proto", fileDescriptor_ae9822aadeb9bcd5)
}

var fileDescriptor_ae9822aadeb9bcd5 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x65, 0x5b, 0x92, 0x26, 0x13, 0xda, 0x48, 0xab, 0xaa, 0x98, 0x54, 0x38, 0x55, 0x24, 0x50,
	0x2f, 0x71, 0x50, 0x8b, 0x38, 0x14, 0x71, 0x49, 0xf9, 0xaa, 0x54, 0xa0, 0x72, 0xca, 0x85, 0x8b,
	0xb5, 0xb1, 0x37, 0xeb, 0x95, 0x12, 0x6f, 0xe4, 0xdd, 0x00, 0xed, 0x85, 0x23, 0x57, 0x8e, 0xfd,
	0x15, 0xfc, 0x06, 0x8e, 0x3d, 0xf2, 0x0b, 0xf8, 0x68, 0xff, 0x04, 0x47, 0xb4, 0x63, 0x2f, 0xa9,
	0x20, 0xe2, 0x62, 0x7b, 0xde, 0xbc, 0xf7, 0xfc, 0x3c, 0xe3, 0x85, 0x5d, 0x21, 0x4d, 0x3a, 0x1b,
	0x06, 0xb1, 0x9a, 0xf4, 0x8e, 0xc3, 0x57, 0x2f, 0xbb, 0xaf, 0x07, 0x3d, 0xa1, 0xba, 0x43, 0x33,
	0xd2, 0xbd, 0x69, 0xae, 0x8c, 0xd2, 0x3d, 0x9d, 0xb2, 0x3c, 0x29, 0xae, 0x01, 0x42, 0xb4, 0x82,
	0x45, 0x6b, 0xef, 0x8a, 0xd6, 0xe4, 0x2a, 0xeb, 0xce, 0xb4, 0xd3, 0x76, 0x63, 0x35, 0x99, 0xa8,
	0xcc, 0x59, 0x88, 0x99, 0xb5, 0xc0, 0x6b, 0x61, 0xd1, 0xba, 0xb7, 0x40, 0x8b, 0x9d, 0xe1, 0x6c,
	0xd4, 0x13, 0x4a, 0x28, 0x2c, 0xf0, 0xa9, 0x54, 0xf8, 0x42, 0x29, 0x31, 0xe6, 0x73, 0x56, 0x32,
	0xcb, 0x99, 0x91, 0x2a, 0x2b, 0xfb, 0xed, 0xbf, 0xfb, 0x46, 0x4e, 0xb8, 0x36, 0x6c, 0x32, 0x2d,
	0x08, 0x9d, 0x3d, 0xa8, 0x0e, 0x0c, 0x33, 0x33, 0x4d, 0x37, 0xa0, 0xaa, 0xf1, 0xc9, 0x23, 0x5b,
	0x64, 0xbb, 0x1e, 0x96, 0x15, 0xf5, 0x60, 0x65, 0xc2, 0xb5, 0x66, 0x82, 0x7b, 0x4b, 0xd8, 0x70,
	0x65, 0xe7, 0xf3, 0x32, 0xd4, 0x5e, 0x70, 0xc3, 0x12, 0x66, 0x18, 0x5d, 0x87, 0x8a, 0xcc, 0x12,
	0xfe, 0x1e, 0xd5, 0x95, 0xb0, 0x28, 0xe8, 0x6d, 0x00, 0xcd, 0xb5, 0x96, 0x2a, 0x8b, 0x64, 0x52,
	0xea, 0xeb, 0x25, 0x72, 0x90, 0xd0, 0x4d, 0xa8, 0x8f, 0xe4, 0x98, 0x47, 0x29, 0xd3, 0xa9, 0xb7,
	0x8c, 0xdd, 0x9a, 0x05, 0x9e, 0x33, 0x9d, 0xd2, 0xbb, 0xd0, 0xc4, 0x91, 0x46, 0x48, 0xd1, 0xf2,
	0x94, 0x7b, 0xd7, 0xb7, 0xc8, 0xf6, 0x72, 0xb8, 0x8a, 0xf0, 0x53, 0x39, 0xe6, 0x03, 0x79, 0xca,
	0xe9, 0x1d, 0x58, 0xd3, 0x46, 0xe5, 0x4c, 0xf0, 0x68, 0xcc, 0x33, 0x61, 0x52, 0xaf, 0x52, 0xd2,
	0x0a, 0xf4, 0x10, 0x41, 0xda, 0x86, 0x46, 0xac, 0x32, 0x93, 0xb3, 0xd8, 0xd8, 0x2c, 0x55, 0x7c,
	0x1b, 0x38, 0xe8, 0x20, 0xa1, 0x2d, 0xa8, 0xe5, 0x3c, 0xe6, 0xf2, 0x2d, 0xcf, 0xbd, 0x95, 0x22,
	0x8b, 0xab, 0xed, 0xd7, 0x4d, 0x73, 0x19, 0x73, 0xaf, 0x86, 0xd6, 0x45, 0x61, 0xe3, 0x1b, 0x65,
	0xd8, 0x38, 0x9a, 0xb2, 0x13, 0xaf, 0x8e, 0x9d, 0x1a, 0x02, 0x47, 0xec, 0x84, 0xee, 0x03, 0x68,
	0xc3, 0x72, 0x13, 0xd9, 0x91, 0x7b, 0xb0, 0x45, 0xb6, 0x1b, 0x3b, 0xad, 0xa0, 0xd8, 0x47, 0xe0,
	0xf6, 0x11, 0x1c, 0xbb, 0x7d, 0xf4, 0x6b, 0xe7, 0xdf, 0xda, 0xd7, 0x3e, 0x7d, 0x6f, 0x93, 0xb0,
	0x8e, 0x3a, 0xdb, 0xa1, 0x87, 0xd0, 0xfc, 0x13, 0xba, 0xfc, 0xb8, 0x06, 0x3a, 0xdd, 0xfa, 0xc7,
	0xe9, 0x71, 0xb9, 0xf9, 0xc2, 0xe8, 0xcc, 0x1a, 0xad, 0x39, 0x6d, 0x31, 0x82, 0xce, 0x47, 0x02,
	0xf5, 0xfd, 0x12, 0xd2, 0xf4, 0x11, 0x6c, 0xa6, 0x6c, 0x3c, 0x8a, 0xb4, 0x14, 0x19, 0x4f, 0x22,
	0xae, 0xe3, 0x5c, 0xbd, 0x8b, 0x9c, 0x04, 0xf7, 0x78, 0x23, 0xf4, 0x2c, 0x65, 0x80, 0x8c, 0x27,
	0x48, 0x70, 0x7a, 0xfa, 0x10, 0x5a, 0x57, 0xe5, 0xf8, 0x1f, 0xcf, 0xd5, 0x4b, 0xa8, 0xbe, 0x39,
	0x57, 0x3f, 0xb3, 0x7d, 0x27, 0xee, 0x7c, 0x80, 0xe6, 0x40, 0x66, 0x82, 0x27, 0xf3, 0x38, 0xf7,
	0x61, 0xe3, 0xbf, 0x49, 0xd6, 0xf5, 0xa2, 0x14, 0x0f, 0x60, 0x6d, 0xc1, 0x9b, 0x1b, 0x3b, 0xcd,
	0xa0, 0x38, 0x58, 0x8e, 0x18, 0xae, 0x8a, 0xab, 0x01, 0xfa, 0xfd, 0x5f, 0x3f, 0x7d, 0x72, 0x7e,
	0xe1, 0x93, 0xaf, 0x17, 0x3e, 0xf9, 0x71, 0xe1, 0x93, 0xb3, 0x4b, 0x9f, 0x7c, 0xb9, 0xf4, 0xc9,
	0xf9, 0xa5, 0x4f, 0x60, 0x55, 0xaa, 0xc0, 0x9e, 0xd8, 0x00, 0xff, 0xb4, 0x3e, 0x0c, 0xec, 0xed,
	0xc8, 0x4e, 0xfa, 0x88, 0xbc, 0x59, 0x41, 0x70, 0x3a, 0x1c, 0x56, 0x71, 0xf6, 0xbb, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x2c, 0xc0, 0xb8, 0x57, 0x2f, 0x04, 0x00, 0x00,
}

func (m *Status) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Status) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Status) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintShard(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintShard(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Metadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Metadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Metadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	n1, err1 := github_com_tron_us_protobuf_types.StdDurationMarshalTo(m.ContractLength, dAtA[i-github_com_tron_us_protobuf_types.SizeOfStdDuration(m.ContractLength):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintShard(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x5a
	n2, err2 := github_com_tron_us_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_tron_us_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintShard(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x52
	if m.TotalPay != 0 {
		i = encodeVarintShard(dAtA, i, uint64(m.TotalPay))
		i--
		dAtA[i] = 0x48
	}
	if m.Price != 0 {
		i = encodeVarintShard(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintShard(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ContractId) > 0 {
		i -= len(m.ContractId)
		copy(dAtA[i:], m.ContractId)
		i = encodeVarintShard(dAtA, i, uint64(len(m.ContractId)))
		i--
		dAtA[i] = 0x32
	}
	if m.StorageLength != 0 {
		i = encodeVarintShard(dAtA, i, uint64(m.StorageLength))
		i--
		dAtA[i] = 0x28
	}
	if m.ShardFileSize != 0 {
		i = encodeVarintShard(dAtA, i, uint64(m.ShardFileSize))
		i--
		dAtA[i] = 0x20
	}
	if len(m.FileHash) > 0 {
		i -= len(m.FileHash)
		copy(dAtA[i:], m.FileHash)
		i = encodeVarintShard(dAtA, i, uint64(len(m.FileHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SessionId) > 0 {
		i -= len(m.SessionId)
		copy(dAtA[i:], m.SessionId)
		i = encodeVarintShard(dAtA, i, uint64(len(m.SessionId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Index != 0 {
		i = encodeVarintShard(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Contracts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Contracts) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Contracts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.HalfSignedGuardContract) > 0 {
		i -= len(m.HalfSignedGuardContract)
		copy(dAtA[i:], m.HalfSignedGuardContract)
		i = encodeVarintShard(dAtA, i, uint64(len(m.HalfSignedGuardContract)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.HalfSignedEscrowContract) > 0 {
		i -= len(m.HalfSignedEscrowContract)
		copy(dAtA[i:], m.HalfSignedEscrowContract)
		i = encodeVarintShard(dAtA, i, uint64(len(m.HalfSignedEscrowContract)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SingedContracts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SingedContracts) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SingedContracts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.GuardContract != nil {
		{
			size, err := m.GuardContract.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintShard(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.SignedEscrowContract) > 0 {
		i -= len(m.SignedEscrowContract)
		copy(dAtA[i:], m.SignedEscrowContract)
		i = encodeVarintShard(dAtA, i, uint64(len(m.SignedEscrowContract)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintShard(dAtA []byte, offset int, v uint64) int {
	offset -= sovShard(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedStatus(r randyShard, easy bool) *Status {
	this := &Status{}
	this.Status = string(randStringShard(r))
	this.Message = string(randStringShard(r))
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedShard(r, 3)
	}
	return this
}

func NewPopulatedMetadata(r randyShard, easy bool) *Metadata {
	this := &Metadata{}
	this.Index = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.Index *= -1
	}
	this.SessionId = string(randStringShard(r))
	this.FileHash = string(randStringShard(r))
	this.ShardFileSize = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.ShardFileSize *= -1
	}
	this.StorageLength = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.StorageLength *= -1
	}
	this.ContractId = string(randStringShard(r))
	this.Receiver = string(randStringShard(r))
	this.Price = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Price *= -1
	}
	this.TotalPay = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.TotalPay *= -1
	}
	v1 := github_com_tron_us_protobuf_types.NewPopulatedStdTime(r, easy)
	this.StartTime = *v1
	v2 := github_com_tron_us_protobuf_types.NewPopulatedStdDuration(r, easy)
	this.ContractLength = *v2
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedShard(r, 12)
	}
	return this
}

func NewPopulatedContracts(r randyShard, easy bool) *Contracts {
	this := &Contracts{}
	v3 := r.Intn(100)
	this.HalfSignedEscrowContract = make([]byte, v3)
	for i := 0; i < v3; i++ {
		this.HalfSignedEscrowContract[i] = byte(r.Intn(256))
	}
	v4 := r.Intn(100)
	this.HalfSignedGuardContract = make([]byte, v4)
	for i := 0; i < v4; i++ {
		this.HalfSignedGuardContract[i] = byte(r.Intn(256))
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedShard(r, 3)
	}
	return this
}

func NewPopulatedSingedContracts(r randyShard, easy bool) *SingedContracts {
	this := &SingedContracts{}
	v5 := r.Intn(100)
	this.SignedEscrowContract = make([]byte, v5)
	for i := 0; i < v5; i++ {
		this.SignedEscrowContract[i] = byte(r.Intn(256))
	}
	if r.Intn(5) != 0 {
		this.GuardContract = guard.NewPopulatedContract(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedShard(r, 3)
	}
	return this
}

type randyShard interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneShard(r randyShard) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringShard(r randyShard) string {
	v6 := r.Intn(100)
	tmps := make([]rune, v6)
	for i := 0; i < v6; i++ {
		tmps[i] = randUTF8RuneShard(r)
	}
	return string(tmps)
}
func randUnrecognizedShard(r randyShard, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldShard(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldShard(dAtA []byte, r randyShard, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateShard(dAtA, uint64(key))
		v7 := r.Int63()
		if r.Intn(2) == 0 {
			v7 *= -1
		}
		dAtA = encodeVarintPopulateShard(dAtA, uint64(v7))
	case 1:
		dAtA = encodeVarintPopulateShard(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateShard(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateShard(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateShard(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateShard(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Status) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Metadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovShard(uint64(m.Index))
	}
	l = len(m.SessionId)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	l = len(m.FileHash)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	if m.ShardFileSize != 0 {
		n += 1 + sovShard(uint64(m.ShardFileSize))
	}
	if m.StorageLength != 0 {
		n += 1 + sovShard(uint64(m.StorageLength))
	}
	l = len(m.ContractId)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	if m.Price != 0 {
		n += 1 + sovShard(uint64(m.Price))
	}
	if m.TotalPay != 0 {
		n += 1 + sovShard(uint64(m.TotalPay))
	}
	l = github_com_tron_us_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovShard(uint64(l))
	l = github_com_tron_us_protobuf_types.SizeOfStdDuration(m.ContractLength)
	n += 1 + l + sovShard(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Contracts) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.HalfSignedEscrowContract)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	l = len(m.HalfSignedGuardContract)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SingedContracts) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SignedEscrowContract)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	if m.GuardContract != nil {
		l = m.GuardContract.Size()
		n += 1 + l + sovShard(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovShard(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozShard(x uint64) (n int) {
	return sovShard(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Status) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShard
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Status: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Status: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShard(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Metadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShard
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Metadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Metadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardFileSize", wireType)
			}
			m.ShardFileSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardFileSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageLength", wireType)
			}
			m.StorageLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StorageLength |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalPay", wireType)
			}
			m.TotalPay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalPay |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_tron_us_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractLength", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_tron_us_protobuf_types.StdDurationUnmarshal(&m.ContractLength, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShard(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Contracts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShard
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Contracts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Contracts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HalfSignedEscrowContract", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HalfSignedEscrowContract = append(m.HalfSignedEscrowContract[:0], dAtA[iNdEx:postIndex]...)
			if m.HalfSignedEscrowContract == nil {
				m.HalfSignedEscrowContract = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HalfSignedGuardContract", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HalfSignedGuardContract = append(m.HalfSignedGuardContract[:0], dAtA[iNdEx:postIndex]...)
			if m.HalfSignedGuardContract == nil {
				m.HalfSignedGuardContract = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShard(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SingedContracts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShard
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SingedContracts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SingedContracts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedEscrowContract", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignedEscrowContract = append(m.SignedEscrowContract[:0], dAtA[iNdEx:postIndex]...)
			if m.SignedEscrowContract == nil {
				m.SignedEscrowContract = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuardContract", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GuardContract == nil {
				m.GuardContract = &guard.Contract{}
			}
			if err := m.GuardContract.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShard(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipShard(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowShard
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShard
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShard
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthShard
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupShard
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthShard
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthShard        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowShard          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupShard = fmt.Errorf("proto: unexpected end of group")
)
