name: ci

on:
  pull_request:
    branches: 
      - 'master'
      - 'release'
  push:
    branches: 
      - 'master'
      - 'release'

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Extract Repo Name Lowercase
        shell: bash
        run: echo "##[set-output name=repo;]$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
        id: extract_repo
      
      # extract branch name
      - 
        name: Extract branch name
        if: github.event_name != 'pull_request' && github.event_name != 'release'
        run: |
          echo IMAGE_TAG=$(echo ${GITHUB_REF#refs/heads/})  >> $GITHUB_ENV
      # extract branch name on pull request
      - 
        name: Extract branch from PR
        if: github.event_name == 'pull_request' && github.event_name != 'release'
        run: |
          echo IMAGE_TAG=$(echo ${GITHUB_HEAD_REF})  >> $GITHUB_ENV
      
       # extract tag name
      - 
        name: Extract git tag
        if: github.event_name == 'release'
        run: |
          echo IMAGE_TAG=$(echo ${GITHUB_REF#refs/tags/})  >> $GITHUB_ENV
      - 
        name: Get Image tag
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${IMAGE_TAG})"
        id: extract_image_tag
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.extract_repo.outputs.repo }}:${{ steps.extract_image_tag.outputs.tag }}
     
      -
        name: Build and push if master
        if: ${{ steps.extract_image_tag.outputs.tag }} == 'master'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.extract_repo.outputs.repo }}:latest
