name: unit-test

on:
  push:
  pull_request:
    branches: 
      - 'master'
      - 'release'

jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          docker image list
          docker build -f Dockerfile.unit_testing -t "btfs:make_unit" .
          docker image list
          docker container run -v ${{ github.workspace }}:/btfs_data --privileged --stop-timeout=300 -i btfs:make_unit
