name: unit-test

on:
  push:
  pull_request:
    branches: 
      - 'master'
      - 'release'

jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract Repo Name Lowercase
        shell: bash
        run: echo "##[set-output name=repo;]$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
        id: extract_repo
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Only Build on PRs
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.unit_testing
          platforms: linux/amd64
          push: false
          tags: btfs:make_unit
      - name: Run tests
        run: docker container run -v $WORKSPACE:/btfs_data --privileged --stop-timeout=300 -i btfs:make_unit
